[package]
name = "guessing_game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
owo-colors = "3.4.0"
rand = "0.8.5"
yansi = "0.5.1"
device_query = "1.1.1"
console = "0.15.0"
